### ISSUE TITLE
Bầu trưởng nhóm, xác định đề tài, tên project

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#1]
mình tiến cử bạn dạ thảo làm nhóm trưởng nha

**Comment by dathaohus** [comment]
Còn mình đề nghị bạn Thủy nhé. Đợi bạn Thu Thảo. xem bạn ấy đề nghị ai rồi mình quyết trưởng nhóm nhé.

**Comment by dathaohus** [comment]
Với có ai nghĩ ra được mình định làm gì chưa? Theo mình thì mình nghĩ làm một trang web quản lý sinh viên( kiểu như trang đào tạo trường mình ý) chúng ta có thể nghĩ thêm những chức năng khác cho trang nữa. Các bạn thấy thế  nào?

**Comment by thuthuy-fjs** [comment]
Web bán hàng thì sao nhỉ?

**Comment by TranThiThuThao1208** [comment]
Mình tiến cử bạn Thủy làm trưởng nhóm nhé.

**Comment by TranThiThuThao1208** [comment]
Thấy ý kiến của các cậu như vậy thì chúng mình chốt là làm về web nhé. Làm về quản lý hay bán hàng nhỉ? Cá nhân tớ thấy web về bán hàng cũng rất hay.

**Comment by dathaohus** [comment]
Theo số đông bạn Thủy làm nhóm trưởng nhé

**Comment by TranThiThuThao1208** [comment]
M.n ơi, mình thống nhất là 1 trang web về quản lý bán hàng nhé

**Comment by dathaohus** [comment]
Ok c =)

**Comment by thuthuy-fjs** [comment]
Mn cho xin cái tên đề tài với đi

**Comment by TranThiThuThao1208** [comment]
M.n ơi giờ mình chọn quản lý bán hàng gì đây nhỉ?

**Comment by thuthuy-fjs** [comment]
vậy chọn web bán hàng nha
mn cho xin cái tên đc k á

**Comment by TranThiThuThao1208** [comment]
Fashion shop được k =))))

**Comment by dathaohus** [comment]
ok

**Comment by TranThiThuThao1208** [comment]
Thế nhóm mình quyết định trưởng nhóm là bạn Trần Thu Thủy, đề tài là lập trình Web còn tên project là Fashion shop nha.
