### ISSUE TITLE
Thêm, sửa, xóa danh mục sản phẩm

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#10]

**Comment by thuthuy-fjs** [comment]
mình đã tạo danh mục sản phẩm bao gồm các trường: name, slug, images, intro, desc trong bảng shop_category
mn chạy php artisan migrate để tạo bảng trong cơ sở dữ liệu nha
nếu có bổ sung thêm gì thì mn cứ nói nha

**Comment by dathaohus** [comment]
ok. mình đã chạy được rồi nhé

**Comment by TranThiThuThao1208** [comment]
MÌnh cũng chạy được rồi nhé.
