### ISSUE TITLE
Thêm, sửa, xóa cho product(sản phẩm) trong mục shop của admin

### ISSUE THREAD

**Issue by dathaohus** [thuytt-hus/SE03-Group11#11]

**Comment by dathaohus** [comment]
Trong phần sản phẩm này mình đã tạo ra bảng shop_product gồm có name , slug, images, intro, price. Các bạn có nghĩ được thêm được cột nào trong bảng này nữa không để mình thêm vào. Mà mình nghĩ nếu admin quản lý sản phẩm thì chắc phần giá mình chia ra làm giá niêm yết với giá bán. Các bạn thấy sao?

**Comment by TranThiThuThao1208** [comment]
https://i.imgur.com/SdX0GfR.png
M.n ơi, khi mình thêm sản phẩm vào trong mục shop của admin thì bị lỗi thế này.

**Comment by TranThiThuThao1208** [comment]
https://i.imgur.com/SdX0GfR.png

**Comment by TranThiThuThao1208** [comment]
[Imgur](https://i.imgur.com/a4I88zN.png)

**Comment by TranThiThuThao1208** [comment]
img src="https://i.imgur.com/a4I88zN.png"

**Comment by TranThiThuThao1208** [comment]
<img src="https://i.imgur.com/a4I88zN.png">

**Comment by TranThiThuThao1208** [comment]
M.n ơi, khi mình thêm sản phẩm trong mục shop của admin thì bị lỗi như thế này
<img src="https://i.imgur.com/a4I88zN.png">

**Comment by TranThiThuThao1208** [comment]
Không biết đây là lỗi gì nhỉ ?

**Comment by dathaohus** [comment]
Đấy là lỗi validate dữ liệu. Mình đã tham khảo trang chủ laravel và fix lỗi rồi tý  mình đẩy code lên lại các cậu pull về máy nhé.
![image](https://user-images.githubusercontent.com/56264880/69913769-d9b99e00-146e-11ea-8d8e-72816d541937.png)

**Comment by dathaohus** [comment]
Còn đây là cách mình fix lỗi là mình vào trang laravel https://laravel.com/docs/6.x/validation , Xong mình copy đoạn code này 
![image](https://user-images.githubusercontent.com/56264880/69913782-31f0a000-146f-11ea-95c5-6688d71a4dea.png) cho vào phần store và update trong ShopCategoryController và sửa lại các trường cho phù hợp với phần danh mục sản phẩm 
![image](https://user-images.githubusercontent.com/56264880/69913869-09b57100-1470-11ea-8141-4d4ce685705f.png)
. Xong lại copy đoạn code này vào file submit.blade trong resources/views/admin/content/shop/category 
![image](https://user-images.githubusercontent.com/56264880/69913846-e4286780-146f-11ea-8537-97506f8cc56e.png). Thế là được

**Comment by TranThiThuThao1208** [comment]
Oke cậu nhé. Cảm ơn cậu nha.

**Comment by thuthuy-fjs** [comment]
ok nha
