### ISSUE TITLE
Submit, edit, delete cho Trang(Page) và Tag trong mục Content của Admin

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#12]
Mình đã hoàn thiện phần submit, edit và delete trong cho Trang (page) rồi nhé. Bảng mình có chia thành các cột là :STT, Tên, Tác Giả, View, Images và Actions. Mọi người thấy như vậy đã ổn chưa hay mình cần thêm cột nào nữa không nhỉ?

**Comment by TranThiThuThao1208** [comment]
Phần Tag mình cũng làm tương tự như phần Page. Mọi người pull về máy xem đã ổn chưa và có cần thêm gì nữa k nhé!

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
ok nha

**Comment by dathaohus** [comment]
ok nha. Nhưng bạn chưa đẩy code lên =)

**Comment by TranThiThuThao1208** [comment]
Push lên rồi nhé =)))
