### ISSUE TITLE
Submit, edit, delete cho Menu và Menu items trong mục Menu của Admin

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#13]
Mình đã hoàn thiện phần Menu trong Menu của Admin.

**Comment by TranThiThuThao1208** [comment]
Còn phần Menu items trong Menu của Admin, sẽ phải tạo ra rất nhiều kiểu Menu items tương ứng với mỗi Links trong mục Kiểu Menu items. Nên tạm thời mình chỉ dừng ở đấy, để đến khi làm xong phần FrontEnd cho khách hàng mình sẽ quay lại xử lý tiếp cho phần này
<img src="https://i.imgur.com/kUvZ20s.png">

**Comment by dathaohus** [comment]
Ok c

**Comment by thuthuy-fjs** [comment]
ok
