### ISSUE TITLE
Tích hợp TinyMCE vào dự án

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#14]
Mình đã tích hợp TinyMCE vào phần Mô tả ngắn và Mô tả trong các mục của Shop, Content, Menu và Global Settings.

**Comment by TranThiThuThao1208** [comment]
Mình đã vào https://www.tiny.cloud/docs/ để tham khảo source code mẫu rồi tích hợp vào project. 
Mọi người có thể truy cập để tìm hiểu thêm nha. 
TinyMCE giúp cho người dùng có thể thay đổi HTML và CSS luôn trong editor ( trong project của chúng ta là phần Mô tả ngắn và Mô tả).

**Comment by TranThiThuThao1208** [comment]
<img src="https://i.imgur.com/uDTeAMo.png">

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Ok nha.
