### ISSUE TITLE
Tích hợp laravel file-manager để quản lý các file trong dự án

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#15]

**Comment by thuthuy-fjs** [comment]
mình đã làm phần media manager để quản lý các file trong dự án.
mình đã tham khảo trên trang https://github.com/UniSharp/laravel-filemanager để tạo.

**Comment by thuytt-hus** [comment]
mọi người pull về để chạy nha

**Comment by thuthuy-fjs** [comment]
<img src="https://i.imgur.com/DrB3FKo.png">

**Comment by thuthuy-fjs** [comment]
mn pull về máy chạy nha

**Comment by dathaohus** [comment]
ok c.

**Comment by TranThiThuThao1208** [comment]
oke c
