### ISSUE TITLE
Lỗi khi tạo trang quản lý khách hàng

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#18]
trong lúc tạo trang quản trị khách hàng mình có gặp lỗi này, mn có ai gặp lỗi này giống mình k vậy?
<img src="https://i.imgur.com/kwtlRGd.png">

**Comment by thuthuy-fjs** [comment]
mình fix đc r nha.
đổi đường dẫn trong file resources/views/admin/content/shop/customer/index.blade.php @extends('customer.layouts.glance') thành @extends('admin.layouts.glance') nha

**Comment by dathaohus** [comment]
Ok c.

**Comment by TranThiThuThao1208** [comment]
Oke cậu nha

**Comment by TranThiThuThao1208** [comment]
src = <img https://i.imgur.com/rDmL9rm.png >
