### ISSUE TITLE
Ghép template login và logout của admin

### ISSUE THREAD

**Issue by dathaohus** [thuytt-hus/SE03-Group11#19]

**Comment by dathaohus** [comment]
![image](https://user-images.githubusercontent.com/56264880/70861006-084d7380-1f5b-11ea-8d04-d8613ba2c75a.png)
lúc vào các danh mục trong admin mình gặp lỗi như thế này

**Comment by dathaohus** [comment]
mình đã tìm ra được cách fix lỗi. là thêm hàm construct khởi tạo trong các controller
![image](https://user-images.githubusercontent.com/56264880/70861074-1b147800-1f5c-11ea-9a8b-0a276b96dcc4.png)
để nó khởi tạo Auth:user

**Comment by dathaohus** [comment]
mình đã tìm ra đc cách fix. là thêm hàm khởi tạo construct vào tất cả các controller. để nó khởi tạo các đối tượng Auth:user   
![image](https://user-images.githubusercontent.com/56264880/70861191-1603f880-1f5d-11ea-8900-bbd06cfaf4eb.png)

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by TranThiThuThao1208** [comment]
Oke nha
