### ISSUE TITLE
Lựa chọn công nghệ và công nghệ sử dụng

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#2]
Mình nghĩ nếu làm web thì nên chọn php, sử dụng php storm để code

**Comment by dathaohus** [comment]
Nếu dùng php thì mình nên sử dụng frameword laravel cho nó tiện. Dùng frameword dễ code hơn? mn nghĩ thế nào?

**Comment by thuthuy-fjs** [comment]
mình ok nha

**Comment by TranThiThuThao1208** [comment]
Oke nha.
