### ISSUE TITLE
Lỗi trong quá trình xây dựng menu cho web

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#24]
Mặc dù k có lỗi nhưng menu k hiển thị đc. Các bạn xem thử xem mình sai chỗ nào nha
<img src="https://i.imgur.com/2VWJIzT.png">

**Comment by TranThiThuThao1208** [comment]
Có phải do cậu thiếu dữ liệu của database k?

**Comment by thuthuy-fjs** [comment]
ok mk fix đc r nha

**Comment by dathaohus** [comment]
ok
