### ISSUE TITLE
Chỉnh sửa thêm phần Menu Items trong Menu của Admin

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#25]
Mình đã chỉnh sửa thêm phần menu item để liên kết giữa menu và cha của menu đó. Cụ thể là mình sẽ đếm tổng số menu_item có cha rồi cập nhật tổng số bản ghi con cho menu item cha. Lúc đầu mình làm thì khi menu nào không có menu cha sẽ bị lỗi như này:

**Comment by TranThiThuThao1208** [comment]
<img src="https://i.imgur.com/5hpW1Wf.png">

**Comment by TranThiThuThao1208** [comment]
Để khắc phục lỗi này mình đã cho đoạn code vào trong 1 hàm if, chỉ khi nào item > 0 thì mới có cha.
<img src="https://i.imgur.com/OpV5bFK.png">

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
ok cái này đợt trc mình cũng có làm nhưng hinh như vẫn chưa khắc phục được. cảm ơn c nhé hehe

**Comment by thuthuy-fjs** [comment]
ok nha
