### ISSUE TITLE
Tạo payment và giỏ hàng (cart)

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#29]
Mình đang tạo phần payment và phần giỏ hàng rồi nhé

**Comment by TranThiThuThao1208** [comment]
Tạo 2 phần này, mình đã tham khảo các source code mẫu.
Cụ thể:
-Payment mình tham khảo phần CheckForm ở HOW TO trên trang https://www.w3schools.com 
-Cart mình tham khảo ở https://p.w3layouts.com/demos/june-2016/13-06-2016/womens_fashion/web/checkout.html

**Comment by dathaohus** [comment]
ok nhé. mình thấy form ok đấy. mình đã commit về chạy thử r

**Comment by thuthuy-fjs** [comment]
ok nha
