### ISSUE TITLE
Chức năng chính của web

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#3]

**Comment by thuthuy-fjs** [comment]
Ngoài thêm, sửa, xóa thì mn có nghĩ thêm đc chức năng nào mới k vậy?

**Comment by TranThiThuThao1208** [comment]
Mình chia làm các chức năng riêng dành cho user và admin. 
Admin là người quản lý trang web, có thể thêm, cập nhật nhật, xóa mặt hàng trên web.
User là người mua, có thể mua ngay hoặc thêm sản phẩm vào giỏ hàng, xóa sản phẩm khỏi giỏ hàng, đánh giá sản phẩm sau khi nhận được hàng.

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Tạm thời mình sẽ làm những chức năng trên trước trong quá trình làm nếu có nghĩ thêm được những chức năng nào hay thì mình thêm vào sau nhé

**Comment by TranThiThuThao1208** [comment]
Oke mình cứ làm những chức năng cơ bản của 1 web đã rồi nghĩ thêm được tính năng gì mình sẽ thảo luận thêm sau.

**Comment by TranThiThuThao1208** [comment]
Về các actor, mình có ý kiến là chia lại thành các actor sau:
-Admin
-Seller
-User
-Shipper
Mọi người thấy thế nào?

**Comment by dathaohus** [comment]
ok
