### ISSUE TITLE
Tạo nội dung cho Content Category và Content Tag

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#30]
Để tạo nội dung cho 2 phần này, mình đã tham khảo source code mẫu của webmag. Mình đã đẩy lên rồi. Mọi người vào xem đã oke chưa nhé.

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Oke nha
