### ISSUE TITLE
Xử lý phần quản trị banners trong admin để quản lý banners bên ngoài

### ISSUE THREAD

**Issue by dathaohus** [thuytt-hus/SE03-Group11#35]

**Comment by dathaohus** [comment]
mình đã làm phần thêm sửa xóa của quản trị banner các bạn commit về chạy xem thế nào nhé.  Mình làm form cũng y nhưng những cái trước thôi

**Comment by dathaohus** [comment]
mình nhận ra 1 vấn đề đáng ra phải tạo  controller trong Controllers/Admin/BannerController nhưng mình đã tạo ngoài thư mục Admin. vẫn chạy được nhưng nó không đúng lắm nên mình sẽ sửa lại nhé

**Comment by dathaohus** [comment]
mình đã sửa lại và commit lên r nhé

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by TranThiThuThao1208** [comment]
Oke nha
