### ISSUE TITLE
Hiển thị thông tin của sản phẩm

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#38]
Hiển thị các thông tin của sản phẩm như tên, giá niêm yết, giá bán, .....

**Comment by thuthuy-fjs** [comment]
mình làm xong r nha mn thử pull về máy xem ok k nha

**Comment by dathaohus** [comment]
oke r nha

**Comment by TranThiThuThao1208** [comment]
Ok
