### ISSUE TITLE
Xử lý phần quản trị đơn hàng

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#46]
Ở phần này mình đã tạo các chức năng chỉnh sửa và xóa đơn hàng từ Admin. Trong mục trạng thái sẽ hiển thị trạng thái hiện tại của đơn hàng như: Chưa thanh toán, đã thanh toán, đang vận chuyển.

**Comment by TranThiThuThao1208** [comment]
Mọi người xem vậy đã ổn chưa nha

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Oke nhé
