### ISSUE TITLE
Xử lý phần Top Product trong HomePage

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#48]
Mình hoàn thành phần này rồi nhé

**Comment by TranThiThuThao1208** [comment]
Mình đã để các sản phẩm nổi bật thuộc 1 số danh mục của web hiển thị trên HomePage. Mọi người thấy vậy được không?

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Ok
