### ISSUE TITLE
Hoàn thiện phần Content Category và Content Tag

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#49]
Trước đó mình đã tạo form cho phần Content Category, Content Tag. Bây giờ mình sẽ thay đổi lại dữ liệu và hoàn thiện nốt phần này.

**Comment by TranThiThuThao1208** [comment]
Mình đã hoàn thiện phần này rồi nhé

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Ok nhé
