### ISSUE TITLE
Thiết kế class diagram

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#5]

**Comment by dathaohus** [comment]
Phần thiết kế class diagram bạn Thu Thảo làm nhé

**Comment by TranThiThuThao1208** [comment]
ok mình đang làm rồi nhé

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by TranThiThuThao1208** [comment]
`img src="C:\Users\User\Downloads\Shop_Online"`

**Comment by TranThiThuThao1208** [comment]
`img src="C:/Users/User/Downloads/Shop_Online.png"`

**Comment by TranThiThuThao1208** [comment]
<img src="C:/Users/User/Downloads/Shop_Online.png">

**Comment by TranThiThuThao1208** [comment]
< img src ="https://drive.google.com/open?id=1GP9MIWWD5fSP3R-3rzYowTnsydH3UtRd" >

**Comment by TranThiThuThao1208** [comment]
< img src="https://drive.google.com/drive/u/0/my-drive" >

**Comment by TranThiThuThao1208** [comment]
<img src="https://i.imgur.com/SdX0GfR.png">

**Comment by TranThiThuThao1208** [comment]
Đây là class diagram mình tạo. Trong quá trình làm web nếu có chỗ nào không ổn mình sẽ chỉnh sửa lại sau nha.

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
ok
