### ISSUE TITLE
Hoàn thành và kết thúc Project

### ISSUE THREAD

**Issue by TranThiThuThao1208** [thuytt-hus/SE03-Group11#52]
Mình thấy dự án của chúng ta về cơ bản là đã hoàn thành gần như đầy đủ các tính năng của một trang web bán hàng.
Nên có lẽ chúng ta tạm kết thúc project tại đây là ổn rồi.
Về sau nếu muốn chúng ta sẽ hoàn thiện và phát triển nó hơn nữa.

**Comment by TranThiThuThao1208** [comment]
Mọi người thấy thế nào?

**Comment by thuthuy-fjs** [comment]
ok nha

**Comment by dathaohus** [comment]
Oke
