### ISSUE TITLE
Tạo và xử lý category

### ISSUE THREAD

**Issue by dathaohus** [thuytt-hus/SE03-Group11#7]

**Comment by thuthuy-fjs** [comment]
mình đã tạo danh mục sản phẩm nha

**Comment by dathaohus** [comment]
ok mình đã xem. đã pull code về máy mình thấy ok r.

**Comment by dathaohus** [comment]
à nhưng có 1 vấn đề như thế này. lúc thêm danh mục ý nếu mình không thêm đầy đủ các cột thì nó sẽ không validate dữ liệu(nghĩa là không submit được dữ liệu) do các trường đấy chúng ta bắt buộc bơm vào cơ sở dữ liệu. 
![image](https://user-images.githubusercontent.com/56264880/69906329-8acf2280-13f4-11ea-9e24-a574a1da7c7a.png)
Nên mình đã tham khảo ở trang web của laravel và sửa lại rồi nhé

**Comment by TranThiThuThao1208** [comment]
Mình cũng xem và thấy ok rồi nhé.
