### ISSUE TITLE
Tạo và xử lý CRUD

### ISSUE THREAD

**Issue by dathaohus** [thuytt-hus/SE03-Group11#8]

**Comment by dathaohus** [comment]
mình đang tạo phần product cho shop của admin. Nhưng lúc thêm nhiều sản phẩm nó chưa phân trang được. Lúc bạn thủy làm category bạn đã xử lý được phân trang bạn chỉ mình cách phân trang với.

**Comment by thuthuy-fjs** [comment]
ok nha
