### ISSUE TITLE
Lỗi trong quá trình tạo trang admin

### ISSUE THREAD

**Issue by thuthuy-fjs** [thuytt-hus/SE03-Group11#9]
Uncaught TypeError: Cannot read property 'addEventListener' of null
Trong quá trình tạo trang admin, mình gặp lỗi này mọi người có thể tìm hiểu rồi cho mình biết đó là nỗi gì được k?

**Comment by dathaohus** [comment]
https://stackoverflow.com/questions/26107125/cannot-read-property-addeventlistener-of-null
bạn có thể đọc lỗi ở trang này xem sửa được không nhé

**Comment by dathaohus** [comment]
vì mình cũng đang bị lỗi đấy

**Comment by thuthuy-fjs** [comment]
ok nha
